export enum KeyShortcut {
    Pencil = 'c',
    Brush = 'w',
    Rectangle = '1',
    Ellipse = '2',
    Polygon = '3',
    Line = 'l',
    Eraser = 'e',
    Eyedropper = 'i',
    RectangleSelect = 'r',
    EllipseSelect = 's',
    Bucket = 'b',
    Text = 't',
    Calligraphy = 'p',
    Spray = 'a',
}
