export const BLACK = '000000';
export const WHITE = 'FFFFFF';
export const DEFAULT_COLOR_OPACITY = 1;
export const MAX_RECENT_COLORS_SIZE = 10;
export const HEX_BASE = 16;
export const RED_POSITION_IN_HEX_STRING = 2;
export const GREEN_POSITION_IN_HEX_STRING = 4;
export const BLUE_POSITION_IN_HEX_STRING = 6;

export const COLOR_PICKER_WIDTH = 400;
export const COLOR_PICKER_HEIGHT = 400;
export const COLOR_PICKER_GRADIENT_DIVISIONS = 6;
export const COLOR_PICKER_GRADIENT_FIRST_DIVISION = 1;
export const COLOR_PICKER_GRADIENT_SECOND_DIVISION = 2;
export const COLOR_PICKER_GRADIENT_THIRD_DIVISION = 3;
export const COLOR_PICKER_GRADIENT_FOURTH_DIVISION = 4;
export const COLOR_PICKER_GRADIENT_FIFTH_DIVISION = 5;
export const COLOR_PICKER_CURSOR_RADIUS = 10;

export const MINIMUM_THICKNESS = 1;
export const MAXIMUM_THICKNESS = 100;
export const DASHED_SEGMENTS = 6;

export const DEFAULT_WIDTH = 1000;
export const DEFAULT_HEIGHT = 800;

export const CANVAS_MIN_WIDTH = 250;
export const CANVAS_MIN_HEIGHT = 250;
export const CANVAS_MARGIN_LEFT = 15;
export const CANVAS_MARGIN_TOP = 20;

export const MAX_COLOR_VALUE = 255;

export const ANGLE_90 = 90;
export const ANGLE_45 = 45;
export const ANGLE_180 = 180;

export const MINIMAL_DISTANCE = 20;

export const DEFAULT_LINE_POINT_SIZE = 20;

export const EYEDROPPER_PREVIEW_CANVAS_WIDTH = 150;
export const EYEDROPPER_PREVIEW_CANVAS_HEIGHT = 150;
export const EYEDROPPER_PREVIEW_SCALE_SIZE = 10;
